### ISSUE TITLE
No Link to Discord server

### ISSUE THREAD

**Issue by jerekjoseph** [wace-vault/collection#3]
I would like to contribute some resources, where it says I can share to your server I do not have a link to said server.

Would appreciate sharing the link to the Discord server. :)

**Comment by wacedungeoner** [comment]
The link to the Discord server isn't public information sorry, but if you want to contribute some files to the repository you can fork the repo and make a merge request.

**Comment by jsun1590** [comment]
@wacedungeoner ur a NERD lol @k9

**Comment by jtruong05** [comment]
wave-vault, is there a reason why the discord server isn't public? is it paid access or do I have to verify my age as a student? Thanks!

**Comment by wace-vault** [comment]
> wave-vault, is there a reason why the discord server isn't public? is it paid access or do I have to verify my age as a student? Thanks!

Neither, it's just a private server; invite link is not public.
